name: Deploy (development)
on:
  push:
    branches: [ development ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_DEV_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'development-backend'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_DEV_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'development-frontend'
          github_token: ${{ secrets.GITHUB_TOKEN }}
